apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: vault-ui
spec:
  entryPoints:
    - websecure
  routes:
    - match: HostSNI(`vault.milantech.live`)  
      services:
        - name: vault
          port: 8200
          weight: 10                # [7]
          terminationDelay: 400     # [8]
          proxyProtocol:            # [9]
            version: 1              # [10]
      tls:                          # [11]
        secretName: vault-milantech-live-tls     # [12]
        options:                    # [13]
          name: opt                 # [14]
        certResolver: vault           # [16]
        domains:                    # [17]
        - main: vault.milantech.live         # [18]
          sans:                     # [19]
          - vault-0.milantech.live
          - vault-1.milantech.live
          - vault-2.milantech.live
        passthrough: true          # [20]