#@ load("@ytt:overlay", "overlay")


#@ def kustomization():
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
#@ end

#@overlay/match by=overlay.subset(kustomization())
#@overlay/remove
---
