#@data/values
---
scaling_factor: 6
app_name: "vault"
app_namespace: "realtime-stg"
certificate_arn: arn:aws:acm:us-west-2:644712362974:certificate/52eae0de-3926-4546-b287-721477592eb5
role_arn: "arn:aws:iam::644712362974:role/node117-playbx-us-west-2"

policies:
- name: root
  rules: path "secret/*" {
    capabilities = ["create", "read", "update", "list"]
    }
- name: slo
  rules: path "secret/slo-service" {
    capabilities = ["create", "read", "update", "delete", "list"]
    }

